#!/usr/bin/env node

/**
* @license Apache-2.0
*
* Copyright (c) 2019 The Stdlib Authors.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

'use strict';

// MODULES //

var fs = require( 'fs' );
var path = require( 'path' );


// VARIABLES //

var ROOT = path.resolve( __dirname, '..' );
var BUILD = path.join( ROOT, 'build' );
var BUNDLE = path.join( ROOT, 'node_modules', '@stdlib', 'stdlib', 'dist', 'stdlib-repl.min.js' );
var DEST = path.join( BUILD, 'bundle.min.js' );


// MAIN //

/**
* Main execution sequence.
*
* @private
*/
function main() {
	// Create a directory for storing the stdlib browser REPL:
	fs.mkdirSync( BUILD );

	// Move the REPL bundle:
	fs.renameSync( BUNDLE, DEST );
}

main();